apiVersion: v2
name: radix-cost-allocation
description: Pull cost data from containers and push to sql server
kubeVersion: ">=1.24.0"
appVersion: 1.3.1-rc.1 # x-patch-semver
version: 1.3.1-rc.1 # x-patch-semver
sources:
  - https://github.com/equinor/radix-cost-allocation
maintainers:
  - name: Omnia Radix Development Team
    email: Radix@StatoilSRM.onmicrosoft.com
